openapi: 3.0.0
info:
  version: 1.0.0
  title: MoneyCat
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/moneycat/moneycat/1.0.0
  - url: 'http://localhost:3000'
tags:
  - name: user
    description: Пользователь
  - name: rate
    description: Курс
  - name: bag
    description: Портфель

paths:
  '/sessions':
    post:
      tags:
        - user
      summary: 'Авторизация пользователя'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: 'Авторизация прошла успешно'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: 'Неправильные данные'
    delete:
      tags:
        - user
      summary: 'Выход из системы'
      responses:
        '200':
          description: 'Выход из системы прошел успешно'
        '401':
          description: 'Нет куки'
    get:
      tags:
        - user
      summary: 'Аутентификация'
      responses:
        '200':
          description: 'Авторизация прошла успешно'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: 'Неправильные данные'
        '401':
          description: 'Не авторизован'
  '/users':
    post:
      tags:
        - user
      summary: 'Регистрация'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                password2:
                  type: string
      responses:
        '201':
          description: Пользователь зарегистрировался
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Ошибка. Неправильные данные
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FieldError'
    get:
      tags:
        - user
      summary: 'Получение данных пользователя'
      parameters:
        - schema:
            type: string
          in: cookie
          name: session_id
          required: true
      responses:
        '200':
          description: Пользователь авторизован
          content:
            application/json:
              schema:
                type: object
                properties:
                  email:
                    type: string
                  id:
                    type: integer
        '401':
          description: Пользователь неавторизован
  '/users/avatar':
    put:
      tags:
        - user
      summary: 'Обновление полей'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: OK
  '/users/password':
    put:
      tags:
        - user
      summary: 'Обновление полей'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChangePassword'
      responses:
        '200':
          description: OK
        '401':
          description: Пользователь неавторизован
        '400':
          description: Ошибка обновления
  '/watchers':
    get:
      tags:
        - rate
      summary: Возвращает список котировок, за которыми следит пользователь
      parameters:
        - in: cookie
          name: session_id
          schema:
            type: string
      responses:
        '200':
          description: Список котировок
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Rate'
  '/rates':
    get:
      tags:
        - rate
      summary: Возвращает список всех валют относительно USD
      description: В случае, если указан initial, то возвращаются значения котировок в начале дня
      parameters:
        - in: query
          name: initial
          required: false
          schema:
            type: boolean
      responses:
        '200':
          description: Список котировок
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    title:
                      type: string
                    value:
                      type: number
  '/rates/{title}':
    get:
      tags:
        - rate
      summary: Получение информации о валюте (история)
      parameters:
        - in: path
          required: true
          name: title
          schema:
            type: string
        - in: query
          name: period
          schema:
            type: string
            example:
              - day
              - week
              - month
              - year
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    datetime:
                      type: string
                      format: date-time
                    value:
                      type: number
  '/income':
    get:
      tags:
        - bag
      summary: Получение дохода за определенный период
      parameters:
        - in: query
          name: period
          schema:
            type: string
            example:
              - day
              - week
              - month
              - year
          required: true
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: number
                example: -500.5
        '401':
          description: UnAuthorize
  '/accounts':
    get:
      tags:
        - bag
      summary: Получение кошельков
      parameters:
        - in: cookie
          name: session_id
          schema:
            type: string
          required: true
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Account'
        '401':
          description: UnAuthorize
    post:
      tags:
        - bag
      summary: Добавление кошельков
      parameters:
        - in: cookie
          name: session_id
          schema:
            type: string
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: USD
      responses:
        '201':
          description: ok
        '401':
          description: unAuth
  '/transactions':
    get:
      tags:
        - bag
      summary: Получение истории транзакций
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transaction'
    post:
      tags:
        - bag
      summary: Перевод из валюты в валюты
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTransaction'
      responses:
        '201':
          description: ok


components:
  schemas:
    CreateTransaction:
      type: object
      required:
        - currency
        - base
        - amount
        - sell
      properties:
        currency:
          type: string
          example: USD
        base:
          type: string
          example: RUB
        amount:
          type: number
          example: 1000
        sell:
          type: boolean
    Transaction:
      type: object
      required:
        - currency
        - base
        - amount
        - sell
        - value
        - datetime
      properties:
        currency:
          type: string
          example: USD
        base:
          type: string
          example: RUB
        value:
          type: number
          example: 76.018
        amount:
          type: number
          example: 1000
        datetime:
          type: string
          format: date-time
        sell:
          type: boolean
    Account:
      type: object
      required:
        - title
        - value
      properties:
        title:
          type: string
          example: USD
        value:
          type: number
          example: 2345234.234
    ChangePassword:
      required:
        - old_password
        - new_password
      properties:
        old_password:
          type: string
        new_password:
          type: string
    User:
      type: object
      required:
        - email
        - avatar
      properties:
        email:
          type: string
        avatar:
          type: string
          format: base64
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    FieldError:
      type: array
      items:
        type: object
        properties:
          field:
            type: string
          errors:
            type: array
            items:
              type: string
    Rate:
      type: object
      properties:
        base_title:
          type: string
          description: Относительно какой валюты
        currency_title:
          type: number
          description: Валюта
      example:
        base_tite: "USD"
        currency_title: "EUR"
