openapi: 3.0.0
info:
  version: 1.0.0
  title: MoneyCat
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/moneycat/moneycat/1.0.0
  - url: 'http://localhost:3000'
tags:
  - name: user
    description: User
  - name: currency
    description: Валюта
  - name: rate
    description: Котировка

paths:
  '/sessions':
    post:
      tags:
        - user
      summary: 'Авторизация пользователя'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: 'Авторизация прошла успешно'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: 'Неправильные данные'
  '/users':
    post:
      tags:
        - user
      summary: 'Регистрация'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                password2:
                  type: string
      responses:
        '201':
          description: Пользователь зарегистрировался
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Ошибка. Неправильные данные
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FieldError'
    put:
      tags:
        - user
      summary: 'Обновление полей'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: OK
    get:
      tags:
        - user
      summary: 'Получение данных пользователя'
      parameters:
        - schema:
            type: string
          in: cookie
          name: sessionid
          required: true
      responses:
        '200':
          description: Пользователь авторизован
          content:
            application/json:
              schema:
                type: object
                properties:
                  email:
                    type: string
                  id:
                    type: integer
        '401':
          description: Пользователь неавторизован
  '/watchers':
    get:
      tags:
        - rate
      summary: Возвращает список котировок, за которыми следит пользователь
      parameters:
        - in: cookie
          name: sessionid
          schema:
            type: string
      responses:
        '200':
          description: Список котировок
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Rate'
  '/change-password':
    put:
      tags:
        - password
      summary: 'Обновление полей'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChangePassword'
      responses:
        '200':
          description: OK
        '401':
          description: Пользователь неавторизован
        '400':
          description: Ошибка обновления
components:
  schemas:
    ChangePassword:
      required:
        - old_password
        - new_password
      properties:
        oldPassword:
          type: string
        newPassword1:
          type: string
        newPassword2:
          type: string
    User:
      type: object
      required:
        - id
        - email
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        email:
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    FieldError:
      type: array
      items:
        type: object
        properties:
          field:
            type: string
          errors:
            type: array
            items:
              type: string
    Rate:
      type: object
      properties:
        base_title:
          type: string
          description: Относительно какой валюты
        currency_title:
          type: number
          description: Валюта
      example:
        base_tite: "USD"
        currency_title: "EUR"
